src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticlesRepository::class)
 */
class Articles
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *
     * @ORM\Column(type="string", length=255)
     */
    private $title;


    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="date")
     */
    private $createdDate;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $metaDescription;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imageEnAvant;

    /**
     * @Assert\Length(
     *     min=10,
     *     max=80,
     *     minMessage="la legende est trop courte",
     *     maxMessage="la legende est trop longue")
     * @ORM\Column(type="string", length=255)
     */
    private $LegendeImageEnAvant;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->createdDate;
    }

    public function setCreatedDate(\DateTimeInterface $createdDate): self
    {
        $this->createdDate = $createdDate;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    public function setMetaDescription(string $metaDescription): self
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImageEnAvant(): ?string
    {
        return $this->imageEnAvant;
    }

    public function setImageEnAvant(string $imageEnAvant): self
    {
        $this->imageEnAvant = $imageEnAvant;

        return $this;
    }

    public function getLegendeImageEnAvant(): ?string
    {
        return $this->LegendeImageEnAvant;
    }

    public function setLegendeImageEnAvant(string $LegendeImageEnAvant): self
    {
        $this->LegendeImageEnAvant = $LegendeImageEnAvant;

        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categories $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Form\ContactFormType;
use App\Form\DemoType;
use App\Repository\ArticlesRepository;
use App\Repository\CategoriesRepository;
use App\Service\mailerService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(Request            $request,
                          ArticlesRepository $articlesRepository,
                          mailerService    $mailer): Response
    {
        $formDemo = $this->createForm(DemoType::class);
        $this->formDemoSend($request, $formDemo, $mailer);

        $lastArticles = $articlesRepository->findLastOne();
        return $this->render('main/index.html.twig', [
            'articles' => $lastArticles,
            'formDemo' => $formDemo->createView(),
            'formDemo1' => $formDemo->createView(),
        ]);
    }

    /**
     * @Route("/actualite/{categorie}", name="blog")
     */
    public function blog(Request              $request,
                                              $categorie,
                         CategoriesRepository $categoriesRepository,
                         ArticlesRepository   $articlesRepository,
                         mailerService    $mailer): Response
    {
        $formDemo = $this->createForm(DemoType::class);
        $this->formDemoSend($request, $formDemo, $mailer);

        if ($categorie == "tous") {
            $articles = $articlesRepository->findAll();
        } else {
            $cat = $categoriesRepository->findOneBy(['Name' => $categorie]);
            $articles = $articlesRepository->findBy(["Categorie" => $cat->getId()]);
        }
        $categories = $categoriesRepository->findAll();

        return $this->render('main/blog.html.twig', [
            'categories' => $categories,
            'articles' => $articles,
            'formDemo' => $formDemo->createView()
        ]);
    }

    /**
     * @Route("/article/{slug}", name="article")
     */
    public function article(Request            $request,
                                               $slug,
                            ArticlesRepository $articlesRepository,
                            mailerService    $mailer): Response
    {
        $formDemo = $this->createForm(DemoType::class);
        $this->formDemoSend($request, $formDemo, $mailer);

        $lastArticles = $articlesRepository->findLastOne();
        $article = $articlesRepository->findOneBy(['slug' => $slug]);
        return $this->render('main/article.html.twig', [
            'article' => $article,
            'articles' => $lastArticles,
            'formDemo' => $formDemo->createView(),
        ]);
    }

    /**
     * @Route("/contact", name="contact")
     */
    public function contact(Request $request, mailerService $mailer): Response
    {
        //contact form
        $form = $this->createForm(ContactFormType::class);
        $this->formContactSend($request, $form, $mailer);
        //demo form
        $formDemo = $this->createForm(DemoType::class);
        $this->formDemoSend($request, $formDemo, $mailer);

        return $this->render('main/contact.html.twig', [
            'form' => $form->createView(),
            'formDemo' => $formDemo->createView(),
        ]);
    }

    /**
     * @Route("/dashboard", name="dashboard")
     */
    public function dashboard(): Response
    {
        return $this->render('main/dashboard.html.twig');
    }


    /**
     * @Route("/solution/1", name="solution_1")
     */
    public function solutionUn(Request $request,
                               mailerService    $mailer): Response
    {
        $formDemo = $this->createForm(DemoType::class);
        $this->formDemoSend($request, $formDemo, $mailer);
        return $this->render('main/solution1.html.twig', [
            'formDemo1' => $formDemo->createView(),
            'formDemo2' => $formDemo->createView(),
        ]);
    }

    /**
     * @Route("/tarif", name="tarif")
     */
    public function tarif(Request $request,
                          mailerService    $mailer): Response
    {
        $formDemo = $this->createForm(DemoType::class);
        $this->formDemoSend($request, $formDemo, $mailer);
        return $this->render('main/tarif.html.twig', [
            'formDemo' => $formDemo->createView()]);
    }

    /**
     * @Route("/tarif-annuel", name="tarif_annuel")
     */
    public function tarifAnnuel(Request $request,
                                mailerService    $mailer): Response
    {
        $formDemo = $this->createForm(DemoType::class);
        $this->formDemoSend($request, $formDemo, $mailer);
        return $this->render('main/tarifAnnuel.html.twig', [
            'formDemo' => $formDemo->createView()]);
    }

    /**
     * @Route("/mention/legales", name="legals")
     */
    public function legals(): Response
    {
        return $this->render('main/legals.html.twig');
    }

    /**
     * @Route("/faq", name="faq")
     */
    public function faq(): Response
    {
        return $this->render('main/faq.html.twig');
    }

    /**
     * @Route("/merci", name="merci")
     */
    public function merci(): Response
    {
        return $this->render('main/merci.html.twig');
    }

    /**
     * @Route("/partenariat", name="partenariat")
     */
    public function partenariat(): Response
    {
        return $this->render('main/partenariat.html.twig');
    }

    /**
     * @Route("/demo", name="demo")
     */
    public function demo(Request $request,
                         mailerService    $mailer): Response
    {
        $form = $this->createForm(ContactFormType::class);
        $this->formDemoSend($request, $form, $mailer);

        return $this->render('main/demo.html.twig', [
            'form' => $form->createView(),
        ]);
    }

//    ******************************************************************************************************************************
    public function formDemoSend(Request $request, $form, mailerService $mailer)
    {
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $mailer->sendDemoMail(
                $form->get('email')->getData());
        }
    }


    public function formContactSend(Request $request, $form, mailerService $mailer)
    {
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $mailer->sendMail(
                $form->get('email')->getData(),
                $form->get('name')->getData(),
                $form->get('message')->getData());
        }
    }
}

templates/main/article.html.twig
{% extends 'base.html.twig' %}
{% block meta %}
    <meta name="description" content="{{ article.metaDescription }}">{% endblock %}
{% block title %}Drivn - {{ article.title }}{% endblock %}

{% block body %}
    {{ include('_includes/_MainNavigation.html.twig') }}
    <section class="container-medium section-article">
        <div class="article">
            <h1>{{ article.title }}</h1>
            <div class="row">
                <p>{{ article.categorie.name }}</p>
                <p>|</p>
                <p>Publié le <span>{{ article.createdDate|date("d-m-Y") }}</span></p>
            </div>
            <div>
                <img src="{{ asset('uploads/'~article.imageEnAvant) }}" alt="{{ article.legendeImageEnAvant }}">
            </div>
        </div>
        <div class="">
            <h2>{{ article.content| raw }}</h2>
        </div>
    </section>

    <section class="container-large section-col">
        <div class="row-1">
            <h2>Les dernières actualités</h2>
            <div class="prevandnext">
                <div class="prev">
                    <img src="{{ asset('img/arrow.svg') }}" alt="">
                </div>
                <div class="next">
                    <img src="{{ asset('img/arrow.svg') }}" alt="">
                </div>
            </div>
        </div>
        <div class="carousel row">
            {% for article in articles %}
                <div class="bloc-article">
                    <div class="cadre-img">
                        <img src="{{ asset('uploads/'~article.imageEnAvant) }}" alt="{{ article.legendeImageEnAvant }}">
                    </div>
                    <div class="cadre-text">
                        <div class="row">
                            <p>{{ article.categorie }}</p>
                            <p>|</p>
                            <p>Publié le <span>{{ article.createdDate|date("d-m-Y") }}</span></p>
                        </div>
                        <h5>{{ article.title }}</h5>
                        <p>{{ article.content|slice(0,200) |striptags|raw }}</p>
                        <a href="{{ path('article',{slug:article.slug}) }}">Lire l'article</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

    <section class="section-bg-demo">
        <div class="section-demo">
            <div class="cadre-demo">
                <div class="col">
                    <div class="row">
                        <h2 class="text-center">Demander votre démo gratuitement</h2>
                        <p class="text-center">Vous êtes intéressé par nos solutions ? Mais vous n'êtes pas encore sûre
                            ! N'hésitez pas à demander notre démo gratuite pour tester nos solutions.</p>
                    </div>
                    <span class="form-demo" >
                        {{ form_start(formDemo, {'attr': {'class': 'form-demo'}}) }}
                        {{ form_row(formDemo.email) }}
                        {{ form_end(formDemo) }}
                    </span>
                </div>
            </div>
        </div>
    </section>
    {{ include('_includes/_Footer.html.twig') }}

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/slick.min.js') }}"></script>
    <script src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/blog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Drivn - Les actualités{% endblock %}

{% block body %}

    {{ include('_includes/_MainNavigation.html.twig') }}
    <section class="container-large section-col">
        <div class="d-flex-column gap-20">
            <h2 class="text-center">Blog</h2>
            <div class="d-flex justify-content-center gap-30">
                <span><a href="{{ path('blog',{categorie: 'tous'}) }}">Tous</a></span>
                {% for categorie in categories %}
                <span><a href="{{ path('blog',{categorie: categorie.name}) }}">{{ categorie.name }}</a></span>

                {% endfor %}
            </div>
        </div>
        <div class="row wrap">
            {% for article in articles %}
            <div class="bloc-article">
                <div class="width430">
                    <img src="{{ asset('uploads/'~article.imageEnAvant) }}" alt="{{ article.legendeImageEnAvant }}">
                </div>
                <div class="cadre-text">
                    <div class="row">
                        <p>{{ article.categorie }}</p>
                        <p>|</p>
                        <p>Publié le <span>{{ article.createdDate|date("d-m-Y") }}</span></p>
                    </div>
                    <h5>{{ article.title }}</h5>
                    <p>{{ article.content|slice(0,200) |striptags|raw }}</p>
                    <a href="{{ path('article',{slug:article.slug}) }}">Lire l'article</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

    <section class="section-bg-demo">
        <div class="section-demo">
            <div class="cadre-demo">
                <div class="col">
                    <div class="row">
                        <h2 class="text-center">Demander votre démo gratuitement</h2>
                        <p class="text-center">Vous êtes intéressé par nos solutions ? Mais vous n'êtes pas encore sûre ! N'hésitez pas à demander notre démo gratuite pour tester nos solutions.</p>
                    </div>
                    <span class="form-demo" >
                        {{ form_start(formDemo, {'attr': {'class': 'form-demo'}}) }}
                        {{ form_row(formDemo.email) }}
                        {{ form_end(formDemo) }}
                    </span>
                </div>
            </div>
        </div>
    </section>
    {{ include('_includes/_Footer.html.twig') }}

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/slick.min.js') }}"></script>
    <script src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Drivn{% endblock %}

{% block body %}

    {{ include('_includes/_MainNavigation.html.twig') }}
    <section class="section-bg-right">
        <div class="container-large section-col">
            <div class="cadre-text d-column gap-20">
                <h1 class="text-center">Contact</h1>
                <p class="text-center">Pout toute demande d’information et prise de contact, vous pouvez nous joindre en
                    remplissant le formulaire de demande de contact. Nous vous répondrons dans les plus brefs
                    délais.</p>
            </div>
            {{ form_start(form) }}
            <div class="form container-small">
                <div class="d-flex-column gap-10">
                    <label for="name">Votre prénom</label>
                    {{ form_row(form.name) }}
                </div>
                <div class="d-flex-column gap-10">
                    <label for="mail">Votre adresse mail</label>
                    {{ form_row(form.email) }}
                </div>
                <div class="d-flex-column gap-10">
                    <label for="messag">Votre demande</label>
                    {{ form_row(form.message) }}
                </div>
                <div>
                    <input class="button-1" type="submit" value="Envoyer ma demande">
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </section>

    <section class="section-bg-demo">
        <div class="section-demo">
            <div class="cadre-demo">
                <div class="col">
                    <div class="row">
                        <h2 class="text-center">Demander votre démo gratuitement</h2>
                        <p class="text-center">Vous êtes intéressé par nos solutions ? Mais vous n'êtes pas encore sûre
                            ! N'hésitez pas à demander notre démo gratuite pour tester nos solutions.</p>
                    </div>
                    <span class="form-demo" >
                        {{ form_start(formDemo, {'attr': {'class': 'form-demo'}}) }}
                        {{ form_row(formDemo.email) }}
                        {{ form_end(formDemo) }}
                    </span>
                </div>
            </div>
        </div>
    </section>
    {{ include('_includes/_Footer.html.twig') }}

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/slick.min.js') }}"></script>
    <script src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Drivn - Accès à votre dashboard{% endblock %}

{% block body %}

    {{ include('_includes/_MainNavigation.html.twig') }}
    <section class="container-large section-col">
        <h1 class="text-center">Accès au dashboard</h1>
        <div>
            <h2 class="text-center">Dashboard</h2>
        </div>
        <div>
            <p class="text-center">Vous souhaitez en faire plus ?</p>
            <a class="text-center d-flex justify-content-center" href="">Accéder au Dashboard depuis l'application web</a>
        </div>
    </section>

    {{ include('_includes/_Footer.html.twig') }}

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/slick.min.js') }}"></script>
    <script src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/demo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Drivn - Demande de démo{% endblock %}

{% block body %}

    {{ include('_includes/_MainNavigation.html.twig') }}
    <section class="container-large section-col">
        <h1>Votre démo gratuite</h1>
        <p>Vous souhaitez tester le logiciel avant de vous lancer ? Pour cela, rien de plus simple, il vous suffit simplement de remplir le formulaire ci-dessous. Dés réception de votre demande de démo, nous vous enverrons les accès à la démo.</p>
    </section>

    <section class="section-bg">
        <div class="container-large section-col-2 overflow">
            <div class="cadre-text">
                <h2 class="font-white">Pourquoi passer par Driv’n ?</h2>
                <ul class="d-flex-column gap-20">
                    <li class="font-bold font-white">✓ Une aide de prise de décision</li>
                    <li class="font-bold font-white">✓ Un tableau de bord personnalisé</li>
                    <li class="font-bold font-white">✓ Accès au logiciel 24h/24 et 7j/7</li>
                </ul>
                <p class="font-white">Ne perdez plus votre temps à prendre des décisions, notre solution vous permet de décider sereinement grâce à des données simplifiées. Vos prises de décision n'auront jamais été aussi simples.</p>
            </div>
            <div class="cadre-text">
                <form class="form" action="">
                    <div class="d-flex-column gap-10">
                        <label class="font-white" for="name">Votre prénom</label>
                        <input type="name" placeholder="Ecrivez votre prénom">
                    </div>
                    <div class="d-flex-column gap-10">
                        <label class="font-white" for="mail">Votre adresse mail</label>
                        <input type="mail" placeholder="Indiquez votre adresse mail">
                    </div>
                    <div class="d-flex-column gap-10">
                        <label class="font-white" for="messag">Votre demande</label>
                        <textarea name="message" id="message" cols="30" rows="10">Vous avez des questions ?</textarea>
                    </div>
                    <div>
                        <input class="button-1" type="submit" value="Envoyer ma demande">
                    </div>
                </form>
            </div>
        </div>
    </section>


    <section class="container-large section-col">
        <div class="row-1">
            <h2>Les avis de nos clients</h2>
            <div class="prevandnext">
                <div class="prev">
                    <img src="{{ asset('img/arrow.svg') }}" alt="">
                </div>
                <div class="next">
                    <img src="{{ asset('img/arrow.svg') }}" alt="">
                </div>
            </div>
        </div>
        <div class="carousel">
            <div class="bloc-avis">
                <div class="d-flex-column gap-20">
                    <p>Adrian a su comprendre le besoin, analyser les possibles pour me proposer des solutions et prendre en compte mes remarques sur la pratique afin d’aboutir à un outil en lien avec mon objectif, sur-mesure</p>
                    <div>
                        <p class="font-bold">Karine</p>
                        <p>Accompagnatrice d’entrepreneurs</p>
                    </div>
                </div>
            </div>
            <div class="bloc-avis">
                <div class="d-flex-column gap-20">
                    <p>Adrian a su comprendre le besoin, analyser les possibles pour me proposer des solutions et prendre en compte mes remarques sur la pratique afin d’aboutir à un outil en lien avec mon objectif, sur-mesure</p>
                    <div>
                        <p class="font-bold">Karine</p>
                        <p>Accompagnatrice d’entrepreneurs</p>
                    </div>
                </div>
            </div>
            <div class="bloc-avis">
                <div class="d-flex-column gap-20">
                    <p>Adrian a su comprendre le besoin, analyser les possibles pour me proposer des solutions et prendre en compte mes remarques sur la pratique afin d’aboutir à un outil en lien avec mon objectif, sur-mesure</p>
                    <div>
                        <p class="font-bold">Karine</p>
                        <p>Accompagnatrice d’entrepreneurs</p>
                    </div>
                </div>
            </div>
            <div class="bloc-avis">
                <div class="d-flex-column gap-20">
                    <p>Adrian a su comprendre le besoin, analyser les possibles pour me proposer des solutions et prendre en compte mes remarques sur la pratique afin d’aboutir à un outil en lien avec mon objectif, sur-mesure</p>
                    <div>
                        <p class="font-bold">Karine</p>
                        <p>Accompagnatrice d’entrepreneurs</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {{ include('_includes/_Footer.html.twig') }}

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/slick.min.js') }}"></script>
    <script src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/faq.html.twig
{% extends 'base.html.twig' %}

{% block title %}Drivn - Toutes vos questions sur Drivn{% endblock %}

{% block body %}

    {{ include('_includes/_MainNavigation.html.twig') }}

    <section class="container-medium section-col">
        <h1>FAQ</h1>
        <div class="d-flex-column gap-40">
            <h2>Inscription au logiciel</h2>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 1 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 2 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 3 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
        </div>
        <div class="d-flex-column gap-40">
            <h2>Utilisation du logiciel</h2>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 1 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 2 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 3 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
        </div>
        <div class="d-flex-column gap-40">
            <h2>Le paiement et la livraison</h2>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 1 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 2 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 3 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 4 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
            <div class="d-flex-column gap-15">
                <h3>Question numéro 5 ?</h3>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est</p>
            </div>
        </div>
    </section>
    {{ include('_includes/_Footer.html.twig') }}

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/slick.min.js') }}"></script>
    <script src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}

templates/main/merci.html.twig
{% extends 'base.html.twig' %}

{% block title %}Drivn{% endblock %}

{% block body %}

    {{ include('_includes/_MainNavigation.html.twig') }}
    <section class="container-medium section-col">
        <div class="cadre-text d-column gap-20">
            <h1 class="text-center"> Merci pour votre abonnement !</h1>
            <p class="text-center">Nous avons reçu votre demande d'abonnement, vous allez donc recevoir un mail avec vos identifiants de connexion. Dès que vous aurez accès au logiciel, vous pourrez intégrer toutes vos données comptables. Si vous avez besoin d'aide, n'hésitez pas à <a href="contact.html">nous contacter</a>.</p>
        </div>
        <div class="d-flex justify-content-center gap-30">
            <a class="button-1" href="">Aller sur la page d'accueil</a>
            <a class="button-2" href="">Voir toutes nos actualités</a>
        </div>
        <div>
            <h2 class="text-center">Restons connectés !</h2>
            <div class="d-flex justify-content-center gap-15">
                <a href="#"><img src="{{ asset('img/facebook.svg') }}" alt=""></a>
                <a href="#"><img src="{{ asset('img/instagram.svg') }}" alt=""></a>
            </div>
        </div>

    </section>

    {{ include('_includes/_Footer.html.twig') }}

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/slick.min.js') }}"></script>
    <script src="{{ asset('js/carousel.js') }}"></script>
{% endblock %}